steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
    - --destination=gcr.io/${_PROJECT_ID}/helloworld
    - --cache=true
    - --cache-ttl=8h
    - --dockerfile=${_DOCKERFILE}

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', '${_DEPLOY_NAME}', '--image', 'gcr.io/${_PROJECT_ID}/helloworld:latest', '--region', 'us-central1', '--allow-unauthenticated']